### ISSUE TITLE
Object spread operator is unexpected

### ISSUE THREAD

**Issue by vaagnavanesyan** [andriijas/react-app-rewire-vendor-splitting#2]
I created project with CRA, added react-app-rewired and react-app-rewire-vendor-splitting. When I tried to start project, I got this:
```
config.entry = { ...config.entry, ...(extractVendors() || {}) };
                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Work\z661nvj7m4\config-overrides.js:1:93)
error Command failed with exit code 1.
```

My ```package.json:```
```
{
  "name": "new",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "homepage": "https://codesandbox.io/s/new",
  "main": "src/index.js",
  "dependencies": {
    "react": "16.2.0",
    "react-app-rewire-vendor-splitting": "1.3.0",
    "react-app-rewired": "1.4.1",
    "react-dom": "16.2.0",
    "react-scripts": "1.1.0"
  },
  "devDependencies": {},
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-app-rewired eject"
  }
}
```
My ```config-overrides.js:```
```
const rewireVendorSplitting = require("react-app-rewire-vendor-splitting");

module.exports = function override(config, env) {
  config = rewireVendorSplitting(config, env);
  return config;
};
```
and ```vendors.js:```
```
module.exports = {
    vendors: [
        "prop-types",
        "react",
        "react-dom",
        "react-router-dom",
        "react-router-redux",
        "react-redux",
        "redux"
    ]
};
```
repo with it: https://github.com/Vahagn1993/z661nvj7m4
Just try to yarn and yarn start. Is it work for you?

**Comment by timstarbuck** [comment]
@Vahagn1993 did you find a solution for this?

**Comment by vaagnavanesyan** [comment]
@timstarbuck it was long ago so I can't be sure for that. If it urgent for you I can find out answer on this weekends

**Comment by vaagnavanesyan** [comment]
@timstarbuck 
I tried again and now it works perfectly
You can check out it [here](https://github.com/Vahagn1993/react-app-rewire-vendor-splitting-example)
May be it was an issue with something else...
